version: '3'

services:
  postgre-db:
    image: postgres
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: filmregister
      POSTGRES_USER: lazzlo74
      POSTGRES_PASSWORD: lazzlo74

  app-server:
    image: filmregister
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgre-db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgre-db/filmregister'
    entrypoint: ['java', '-jar', 'filmregister.jar']