drop table if exists MOVIES CASCADE;
drop table if exists GENRES CASCADE;
drop table if exists DIRECTORS CASCADE;
drop table if exists CODEC_FORMATS CASCADE;
drop table if exists AUDIOS CASCADE;
drop table if exists SUBTITLES CASCADE;
drop table if exists STORAGE_TYPES CASCADE;

CREATE TABLE movies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   title_hun VARCHAR(255),
   title_english VARCHAR(255),
   title_original VARCHAR(255),
   duration TIME WITHOUT TIME ZONE,
   genre_id BIGINT,
   director_id BIGINT,
   release_year INTEGER,
   codec_format_id BIGINT,
   x_resolution INTEGER,
   y_resolution INTEGER,
   storage_type_id BIGINT,
   storage_number INTEGER,
   CONSTRAINT pk_movies PRIMARY KEY (id)
);

CREATE TABLE genres (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_genres PRIMARY KEY (id)
);

CREATE TABLE directors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   birthday date,
   CONSTRAINT pk_directors PRIMARY KEY (id)
);

CREATE TABLE codec_formats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_codec_formats PRIMARY KEY (id)
);

CREATE TABLE audios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   language VARCHAR(255),
   CONSTRAINT pk_audios PRIMARY KEY (id)
);

CREATE TABLE subtitles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   language VARCHAR(255),
   CONSTRAINT pk_subtitles PRIMARY KEY (id)
);

CREATE TABLE storage_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_storage_types PRIMARY KEY (id)
);

INSERT
INTO
  movies
  (TITLE_HUN, TITLE_ORIGINAL, DURATION, RELEASE_YEAR)
VALUES
  ('Legyetek jók ha tudtok', 'Stat buoni se potete', '02:19:17', 1983);

INSERT
INTO
  movies
  (TITLE_HUN, TITLE_ENGLISH, DURATION, RELEASE_YEAR)
VALUES
  ('A segítség', 'The help', '02:26:20', 2011);

insert into genres (name) values ('akció');
insert into genres (name) values ('vígjáték');
insert into genres (name) values ('dráma');
insert into genres (name) values ('történelmi');
insert into genres (name) values ('western');
insert into genres (name) values ('fantasy');
insert into genres (name) values ('sci-fi');
insert into genres (name) values ('horror');
insert into genres (name) values ('thriller');
insert into genres (name) values ('romantikus');
insert into genres (name) values ('rajzfilm');
insert into genres (name) values ('anime');
insert into genres (name) values ('dokumentum');
insert into genres (name) values ('természet-film');
insert into genres (name) values ('utifilm');
insert into genres (name) values ('háborús-film');
insert into genres (name) values ('némafilm');

insert into codec_formats (name) values ('H264-BRRIP');
insert into codec_formats (name) values ('H264-WEBRIP');
insert into codec_formats (name) values ('H264-1080P');
insert into codec_formats (name) values ('H264-720P');
insert into codec_formats (name) values ('H265');
insert into codec_formats (name) values ('H265-4K');
insert into codec_formats (name) values ('XVID');
insert into codec_formats (name) values ('DIVX');
insert into codec_formats (name) values ('VHS');
insert into codec_formats (name) values ('DVD');
insert into codec_formats (name) values ('BLURAY');

insert into storage_types (name) values ('HDD');
insert into storage_types (name) values ('VHS-KAZETTA');
insert into storage_types (name) values ('DVD-LEMEZ');
insert into storage_types (name) values ('BLURAY-LEMEZ');

insert into audios (language) values ('magyar');
insert into audios (language) values ('angol');
insert into audios (language) values ('koreai');
insert into audios (language) values ('kínai');
insert into audios (language) values ('japán');

insert into subtitles (language) values ('magyar');
insert into subtitles (language) values ('magyar-kiegészítő');
insert into subtitles (language) values ('angol');
insert into subtitles (language) values ('angol-kiegészítő');

insert into directors (name, birthday) values ('Luigi Magni', '1928-03-21');
insert into directors (name, birthday) values ('Tate Taylor', '1969-06-03');

